language: node_js
node_js:
  - '10'

cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - npm install

before_script:

script:
  - npm run build

after_script:
  - cd ./dist

branches:
  only:
    - master

notifications:
  email: false
