const user = {
  UPDATE_USER_NAME: 'UPDATE_USER_NAME',
  UPDATE_REGISTER_STATE: 'UPDATE_REGISTER_STATE',
  SET_TOKEN: 'SET_TOKEN',
  REMOVE_TOKEN: 'REMOVE_TOKEN'
};

const app = {
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR'
};

export { user, app };
